import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <h1>This is header</h1>
        <div className="flex justify-around">
          <div>
            <h1>Side Menu</h1>
          </div>
          <div>{children}</div>
        </div>
      <h1>This is footer</h1>      
      </body>
    </html>
  );
}
